R2023.09
DigitaleGesellschaft/Datenauskunftsbegehren-Data pull request #20
Opened 2023-08-09 19:59 UTC by nielsson4711

2023-08-13 08:49 UTC, datenreisen commented on data/followups/data_correction.yml
Könnte hier bereits der überarbeitete Text übernommen werden? https://wiki.digitale-gesellschaft.ch/pages/viewpage.action?pageId=382337032

2023-08-13 08:50 UTC, datenreisen commented on data/followups/data_deletion.yml
Könnte hier bereits der überarbeitete Text übernommen werden? https://wiki.digitale-gesellschaft.ch/pages/viewpage.action?pageId=382337032

2023-08-13 08:51 UTC, datenreisen commented on data/followups/incomplete_answer.yml
Könnte hier bereits der überarbeitete Text übernommen werden? https://wiki.digitale-gesellschaft.ch/x/BQDKFg

2023-08-13 08:51 UTC, datenreisen commented on data/followups/unanswered.yml
Könnte hier bereits der überarbeitete Text übernommen werden? https://wiki.digitale-gesellschaft.ch/x/BQDKFg

2023-08-13 08:53 UTC, datenreisen requested changes
Vielen Dank!

2023-08-13 16:46 UTC, nielsson4711 commented on data/followups/unanswered.yml
Die Brieftexte sind im "application code" enthalten. Ob sie beim mehrsprachigen Ausbau von dort in "-data" intergriert werden, oder als Textstrukturen im "app code" verbleiben, ist später zu entscheiden. Um der momentanen Hausruhe willen baute ich die Texte hier ein - sie werden aktuell im appcode nicht verwendet.

2023-08-13 16:46 UTC, nielsson4711 commented on data/followups/incomplete_answer.yml
Die Brieftexte sind im "application code" enthalten. Ob sie beim mehrsprachigen Ausbau von dort in "-data" intergriert werden, oder als Textstrukturen im "app code" verbleiben, ist später zu entscheiden. Um der momentanen Hausruhe willen baute ich die Texte hier ein - sie werden aktuell im appcode nicht verwendet.

2023-08-13 16:46 UTC, nielsson4711 commented on data/followups/data_deletion.yml
Die Brieftexte sind im "application code" enthalten. Ob sie beim mehrsprachigen Ausbau von dort in "-data" intergriert werden, oder als Textstrukturen im "app code" verbleiben, ist später zu entscheiden. Um der momentanen Hausruhe willen baute ich die Texte hier ein - sie werden aktuell im appcode nicht verwendet.

2023-08-13 16:46 UTC, nielsson4711 commented on data/followups/data_correction.yml
Die Brieftexte sind im "application code" enthalten. Ob sie beim mehrsprachigen Ausbau von dort in "-data" intergriert werden, oder als Textstrukturen im "app code" verbleiben, ist später zu entscheiden. Um der momentanen Hausruhe willen baute ich die Texte hier ein - sie werden aktuell im appcode nicht verwendet.

2023-08-27 12:44 UTC, nielsson4711 commented on data/followups/data_correction.yml
Die Texte musste ich wieder aus den Daten herausnehmen, da sie bei den Brieftexten Fehler produzieren. Ursache sind die eng auf die Variabilität der Unternehmens begrenzten Fähigkeiten zur Verarbeitung von Textabsätzen und Variablen im Code. Eine Ausweitung auf die Brieftexte im Allgemeinen setzt umfangreiche Anpassungen voraus.

2023-08-27 12:45 UTC, closed without merging